### ISSUE TITLE
4 out of 8 tests fail with is-descriptor 2.0.0

### ISSUE THREAD

**Issue by simevo** [jonschlinkert/define-property#3]
you don't see that in travis [because is-descriptor 2.0 hasn't been pushed to npm registry](https://github.com/jonschlinkert/is-descriptor/issues/6):
```
mocha -R spec

  define
    ✓ should define a property and make it non-enumerable:
    ✓ should allow any arbitrary value to be assigned:
    1) should define a property with accessor descriptors:
    2) should define a property on a function
    3) should define a property on an array
    4) should define a property on an error
    ✓ should define a property with data descriptors:
    ✓ should throw an error when invalid args are passed:


  4 passing (20ms)
  4 failing

  1) define
       should define a property with accessor descriptors::

      AssertionError [ERR_ASSERTION]: 'bar' == 'baz'
      + expected - actual

      -bar
      +baz
      
      at Context.<anonymous> (test.js:40:12)                                                 
      at callFn (/usr/lib/nodejs/mocha/lib/runnable.js:354:21)                               
      at Test.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:346:7)                     
      at Runner.runTest (/usr/lib/nodejs/mocha/lib/runner.js:442:10)                         
      at /usr/lib/nodejs/mocha/lib/runner.js:560:12                                          
      at next (/usr/lib/nodejs/mocha/lib/runner.js:356:14)                                   
      at /usr/lib/nodejs/mocha/lib/runner.js:366:7                                           
      at next (/usr/lib/nodejs/mocha/lib/runner.js:290:14)                                   
      at Immediate.<anonymous> (/usr/lib/nodejs/mocha/lib/runner.js:334:5)                   

  2) define
       should define a property on a function:

      AssertionError [ERR_ASSERTION]: 'bar' == 'baz'
      + expected - actual

      -bar
      +baz
      
      at Context.<anonymous> (test.js:56:12)                                                 
      at callFn (/usr/lib/nodejs/mocha/lib/runnable.js:354:21)                               
      at Test.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:346:7)                     
      at Runner.runTest (/usr/lib/nodejs/mocha/lib/runner.js:442:10)                         
      at /usr/lib/nodejs/mocha/lib/runner.js:560:12                                          
      at next (/usr/lib/nodejs/mocha/lib/runner.js:356:14)                                   
      at /usr/lib/nodejs/mocha/lib/runner.js:366:7                                           
      at next (/usr/lib/nodejs/mocha/lib/runner.js:290:14)                                   
      at Immediate.<anonymous> (/usr/lib/nodejs/mocha/lib/runner.js:334:5)                   

  3) define
       should define a property on an array:

      AssertionError [ERR_ASSERTION]: 'bar' == 'baz'
      + expected - actual

      -bar
      +baz
      
      at Context.<anonymous> (test.js:72:12)
      at callFn (/usr/lib/nodejs/mocha/lib/runnable.js:354:21)
      at Test.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:346:7)
      at Runner.runTest (/usr/lib/nodejs/mocha/lib/runner.js:442:10)
      at /usr/lib/nodejs/mocha/lib/runner.js:560:12
      at next (/usr/lib/nodejs/mocha/lib/runner.js:356:14)
      at /usr/lib/nodejs/mocha/lib/runner.js:366:7
      at next (/usr/lib/nodejs/mocha/lib/runner.js:290:14)
      at Immediate.<anonymous> (/usr/lib/nodejs/mocha/lib/runner.js:334:5)

  4) define
       should define a property on an error:

      AssertionError [ERR_ASSERTION]: 'bar' == 'baz'
      + expected - actual

      -bar
      +baz
      
      at Context.<anonymous> (test.js:88:12)
      at callFn (/usr/lib/nodejs/mocha/lib/runnable.js:354:21)
      at Test.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:346:7)
      at Runner.runTest (/usr/lib/nodejs/mocha/lib/runner.js:442:10)
      at /usr/lib/nodejs/mocha/lib/runner.js:560:12
      at next (/usr/lib/nodejs/mocha/lib/runner.js:356:14)
      at /usr/lib/nodejs/mocha/lib/runner.js:366:7
      at next (/usr/lib/nodejs/mocha/lib/runner.js:290:14)
      at Immediate.<anonymous> (/usr/lib/nodejs/mocha/lib/runner.js:334:5)
```

**Comment by jonschlinkert** [comment]
> you don't see that in travis because is-descriptor 2.0 hasn't been pushed to npm registry:

lol, it seems obvious that is-descriptor 2.0 hasn't been pushed to NPM because tests fail.

**Comment by SnarkBoojum** [comment]
Uh... so they put the tag on a known-broken release!?
